export const HOME = {
    GET_PRODUCTS: 'HOME.GET_PRODUCTS',
    GET_PRODUCTS_SUCCESS: 'HOME.GET_PRODUCTS_SUCCESS',
    GET_PRODUCTS_ERROR: 'HOME.GET_PRODUCTS_ERROR',
    HYDRATE: 'HOME.HYDRATE',
}

export const PRODUCT = {
    ADD_TO_CART: 'PRODUCT.ADD_TO_CART',
    ADDED_TO_CART: 'PRODUCT.ADDED_TO_CART',
    GET_CART: 'PRODUCT.GET_CART',
    GET_CART_SUCCESS: 'PRODUCT.GET_CART_SUCCESS',
    GET_PRODUCT: 'PRODUCT.GET_PRODUCT',
    GET_PRODUCT_SUCCESS: 'PRODUCT.GET_PRODUCT_SUCCESS',
    GET_PRODUCT_ERROR: 'PRODUCT.GET_PRODUCT_ERROR',
    CREATE_PRODUCT: 'PRODUCT.CREATE_PRODUCT',
    CREATE_PRODUCT_SUCCESS: 'PRODUCT.CREATE_PRODUCT_SUCCESS',
    CREATE_PRODUCT_ERROR: 'HOME.CREATE_PRODUCT_ERROR',
    DELETE_PRODUCT: 'PRODUCT.DELETE_PRODUCT',
    DELETE_PRODUCT_SUCCESS: 'PRODUCT.DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_ERROR: 'PRODUCT.DELETE_PRODUCT_ERROR',
}